"""UrlCheck last_modified deleted

Revision ID: 173148c4c04e
Revises: 56d054867286
Create Date: 2023-04-22 11:31:40.603094

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '173148c4c04e'
down_revision = '56d054867286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_check', schema=None) as batch_op:
        batch_op.drop_column('last_modified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_check', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
