"""init

Revision ID: c4c3e36f89c4
Revises:
Create Date: 2024-12-09 12:59:52.519925

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "c4c3e36f89c4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "email", sqlalchemy_utils.types.email.EmailType(length=255), nullable=False
        ),
        sa.Column(
            "password",
            sqlalchemy_utils.types.password.PasswordType(max_length=255),
            nullable=False,
        ),
        sa.Column(
            "is_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
        sa.UniqueConstraint("email", name=op.f("users_email_key")),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("projects_user_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("projects_pkey")),
    )
    op.create_table(
        "sites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column(
            "options",
            sqlalchemy_utils.types.json.JSONType(),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("index_page_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("sites_project_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("sites_pkey")),
        sa.UniqueConstraint("domain", name=op.f("sites_domain_key")),
    )
    op.create_table(
        "pages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), server_default="", nullable=False),
        sa.Column(
            "description", sa.String(length=255), server_default="", nullable=False
        ),
        sa.Column("keywords", sa.String(length=255), server_default="", nullable=False),
        sa.Column("heading", sa.String(length=255), server_default="", nullable=False),
        sa.Column("excerpt", sa.String(), server_default="", nullable=False),
        sa.Column("content", sa.String(), server_default="", nullable=False),
        sa.Column("image", sa.String(length=255), server_default="", nullable=False),
        sa.Column("template", sa.String(length=255), server_default="", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["pages.id"],
            name=op.f("pages_parent_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("pages_site_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pages_pkey")),
        sa.UniqueConstraint("site_id", "name", name="sections_site_id_name_key"),
        sa.UniqueConstraint("site_id", "slug", name="sections_site_id_slug_key"),
    )
    op.create_table(
        "extracts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("extracts_project_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("extracts_pkey")),
    )
    op.create_table(
        "resources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("resources_project_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("resources_pkey")),
    )
    op.create_table(
        "pages_extracts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("extract_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["extract_id"],
            ["extracts.id"],
            name=op.f("pages_extracts_extract_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["pages.id"],
            name=op.f("pages_extracts_page_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pages_extracts_pkey")),
        sa.UniqueConstraint(
            "page_id", "extract_id", name="pages_extracts_page_id_extract_id_key"
        ),
    )
    op.create_table(
        "resources_extracts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=False),
        sa.Column("extract_id", sa.Integer(), nullable=False),
        sa.Column("selector", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["extract_id"],
            ["extracts.id"],
            name=op.f("resources_extracts_extract_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
            name=op.f("resources_extracts_resource_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("resources_extracts_pkey")),
        sa.UniqueConstraint(
            "resource_id",
            "extract_id",
            name="resources_extracts_resource_id_extract_id_key",
        ),
    )
    op.create_table(
        "sites_extracts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("extract_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=255), nullable=False),
        sa.Column(
            "is_preview", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["extract_id"],
            ["extracts.id"],
            name=op.f("sites_extracts_extract_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("sites_extracts_site_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("sites_extracts_pkey")),
        sa.UniqueConstraint(
            "site_id", "extract_id", name="sites_extracts_site_id_extract_id_key"
        ),
    )
    op.create_table(
        "urls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=False),
        sa.Column("address", sqlalchemy_utils.types.url.URLType(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
            name=op.f("urls_resource_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("urls_pkey")),
        sa.UniqueConstraint(
            "resource_id", "address", name="urls_resource_id_address_key"
        ),
    )
    op.create_table(
        "pages_urls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("url_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["pages.id"],
            name=op.f("pages_urls_page_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["url_id"],
            ["urls.id"],
            name=op.f("pages_urls_url_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pages_urls_pkey")),
        sa.UniqueConstraint("page_id", "url_id", name="pages_urls_page_id_url_id_key"),
    )
    op.create_table(
        "urls_extracts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url_id", sa.Integer(), nullable=False),
        sa.Column("extract_id", sa.Integer(), nullable=False),
        sa.Column("draft", sa.String(), server_default="", nullable=False),
        sa.Column("data", sa.String(), server_default="", nullable=False),
        sa.Column("draft_modified_at", sa.DateTime(), nullable=True),
        sa.Column("data_modified_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["extract_id"],
            ["extracts.id"],
            name=op.f("urls_extracts_extract_id_fkey"),
            ondelete="cascade",
        ),
        sa.ForeignKeyConstraint(
            ["url_id"],
            ["urls.id"],
            name=op.f("urls_extracts_url_id_fkey"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("urls_extracts_pkey")),
        sa.UniqueConstraint(
            "url_id", "extract_id", name="urls_extracts_url_id_extract_id_key"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("urls_extracts")
    op.drop_table("pages_urls")
    op.drop_table("urls")
    op.drop_table("sites_extracts")
    op.drop_table("resources_extracts")
    op.drop_table("pages_extracts")
    op.drop_table("resources")
    op.drop_table("extracts")
    op.drop_table("projects")
    op.drop_table("users")
    op.drop_table("sites")
    op.drop_table("pages")
    # ### end Alembic commands ###
