"""site template

Revision ID: 575d0da609aa
Revises: 937a69d4a0ce
Create Date: 2024-12-14 18:56:09.164264

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "575d0da609aa"
down_revision = "937a69d4a0ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sites", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "template", sa.String(length=255), server_default="", nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sites", schema=None) as batch_op:
        batch_op.drop_column("template")

    # ### end Alembic commands ###
