"""site index page

Revision ID: 937a69d4a0ce
Revises: c4c3e36f89c4
Create Date: 2024-12-09 13:19:00.092953

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "937a69d4a0ce"
down_revision = "c4c3e36f89c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sites", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("sites_index_page_id_fkey"),
            "pages",
            ["index_page_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sites", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("sites_index_page_id_fkey"), type_="foreignkey"
        )

    # ### end Alembic commands ###
