"""Page.detail_template

Revision ID: c9efdcd68473
Revises: 575d0da609aa
Create Date: 2025-01-19 18:16:26.653015

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c9efdcd68473"
down_revision = "575d0da609aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pages", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "detail_template",
                sa.String(length=255),
                server_default="",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pages", schema=None) as batch_op:
        batch_op.drop_column("detail_template")

    # ### end Alembic commands ###
