"""DataframeCluster pk, DataframeProperty relationships

Revision ID: 3626f8e87091
Revises: cd4cedd282dd
Create Date: 2023-03-27 18:26:34.528225

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '3626f8e87091'
down_revision = 'cd4cedd282dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataframe_cluster', schema=None) as batch_op:
        batch_op.alter_column('dataframe_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cluster_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('unique_dataframe_id_cluster_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataframe_cluster', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_dataframe_id_cluster_id', ['dataframe_id', 'cluster_id'])
        batch_op.alter_column('cluster_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('dataframe_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
