"""Added: id as a primary key and unique constraint to m2m models instead of double fk as a pk

Revision ID: a1c8d67689b8
Revises: bde529d29d99
Create Date: 2022-12-08 18:34:09.888566

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'a1c8d67689b8'
down_revision = 'bde529d29d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_check', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('unique_url_id_check_id', ['url_id', 'check_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_check', schema=None) as batch_op:
        batch_op.drop_constraint('unique_url_id_check_id', type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
