"""Added: UrlCheck extracted_data, last_modified

Revision ID: a78b80ab4b8f
Revises: 43bd10fdaa72
Create Date: 2022-12-05 18:11:39.975217

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'a78b80ab4b8f'
down_revision = '43bd10fdaa72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_check', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extracted_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_modified', sa.DateTime(), nullable=True))
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_check', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('last_modified')
        batch_op.drop_column('extracted_data')
        batch_op.drop_column('raw_data')

    # ### end Alembic commands ###
