"""UrlCheck 'extracted_data' column deleted

Revision ID: a94ccc8ee823
Revises: 3626f8e87091
Create Date: 2023-03-31 14:08:01.809625

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'a94ccc8ee823'
down_revision = '3626f8e87091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_check', schema=None) as batch_op:
        batch_op.drop_column('extracted_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_check', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_data', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
