"""Added: Check.selectors

Revision ID: bde529d29d99
Revises: a78b80ab4b8f
Create Date: 2022-12-05 18:49:29.806198

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'bde529d29d99'
down_revision = 'a78b80ab4b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selectors', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check', schema=None) as batch_op:
        batch_op.drop_column('selectors')

    # ### end Alembic commands ###
