"""Active check - one to one between Dataframe and Check

Revision ID: c101b58fbcd8
Revises: a1c8d67689b8
Create Date: 2022-12-12 19:49:18.220393

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'c101b58fbcd8'
down_revision = 'a1c8d67689b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataframe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'check', ['check_id'], ['id'], ondelete='set null', use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataframe', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('check_id')

    # ### end Alembic commands ###
