"""Cluster nullable fields

Revision ID: daebd432d878
Revises: 9fca2379a861
Create Date: 2022-12-27 12:47:03.574517

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'daebd432d878'
down_revision = '9fca2379a861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cluster', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('excerpt',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cluster', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('text',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('excerpt',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
