"""Property models

Revision ID: e9817f26bb5b
Revises: 341607c3e828
Create Date: 2023-03-22 15:13:03.400264

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'e9817f26bb5b'
down_revision = '341607c3e828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataframe_property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataframe_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('selector', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['dataframe_id'], ['dataframe.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataframe_id', 'property_id', name='unique_dataframe_id_property_id')
    )
    op.create_table('url_property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['dataframe_check.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['url_id'], ['url.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_id', 'check_id', 'property_id', name='unique_url_check_property')
    )
    with op.batch_alter_table('dataframe', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'dataframe_check', ['check_id'], ['id'], ondelete='set null', use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataframe', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('url_property')
    op.drop_table('dataframe_property')
    op.drop_table('property')
    # ### end Alembic commands ###
